name: Build and Push Docker Image
on:
  push:
    branches: [ main ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Aqui criamos as duas tags exigidas: a com o SHA do commit e a 'latest'
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/calculadora-actions:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/calculadora-actions:latest