name: Jobs Encadeados
on:
  push:
    branches: [ main, dev ] # Adicionei 'dev' para você poder testar a restrição do 'if' depois, se quiser
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando ESLint..."
      
  test:
    needs: lint # O test só inicia se o lint passar
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando testes com Jest..."
      
  build:
    needs: test # O build só inicia se o test passar
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simulando build da aplicação..."
      
  deploy:
    needs: build # O deploy só inicia se o build passar
    if: github.ref == 'refs/heads/main' # Regra de ouro: Só faz deploy se a branch for a main
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simulando deploy em produção..."