name: Jobs Encadeados
on:
  push:
    branches: [ main, dev ] 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando ESLint..."
      
  test:
    needs: lint 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando testes com Jest..."
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simulando build da aplicação..."
      
  deploy:
    needs: build 
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simulando deploy em produção..."